### ISSUE TITLE
Partial merkle tree validation

### ISSUE THREAD

**Issue by fanatid** [mappum/bitcoin-merkle-proof#1]
Why you don't check that all bytes from flags array were consumed?
I see checks only for all hashes were consumed and computed root node equal to header merkle root.

**EDIT**: do you planning add partial merkle tree generation?

**Comment by mappum** [comment]
> Why you don't check that all bytes from flags array were consumed?

Good point, I'll add that :+1:

> do you planning add partial merkle tree generation?

I haven't needed that, but you're right that it would go well in this module. That could be useful if we ever need to generate proofs about UTXOs.

**Comment by mappum** [comment]
Resolved in e71353403e9dd49239a742d2bbf6404d901908fb
