### ISSUE TITLE
Current project name

### ISSUE THREAD

**Issue by fanatid** [mappum/bitcoin-merkle-proof#3]
Why not bitcoin-partial-merkle-tree? I think it's more suitable.

**Comment by mappum** [comment]
Good point. I think `bitcoin-merkle-proof` might be better.

**Comment by fanatid** [comment]
Something like this already exist: https://github.com/ethers/bitcoin-proof

**Comment by mappum** [comment]
Renamed to `bitcoin-merkle-proof`
